#端口
server:
  port: 9000

x-route:
  enabled: true

spring:
  application:
    name: gateway-server  # 应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test-consumer-service
          uri: lb://test-consumer
          predicates: 
            - Path=/test-consumer/**
          filters:
            - StripPrefix=1
        - id: test-provider-service
          uri: lb://test-provider
          predicates: 
            - Path=/test-provider/**
          filters:
            - StripPrefix=1